package com.sitrshield.core

import com.sitrshield.core.gate.Gate
import com.sitrshield.core.gate.GateContext
import com.sitrshield.core.gate.HouseholdRole
import com.sitrshield.core.gate.MutationKind
import com.sitrshield.core.gate.MutationVerdict
import com.sitrshield.core.household.Household
import com.sitrshield.core.pin.Pin
import com.sitrshield.core.sync.PairingCode
import com.sitrshield.core.sync.SyncCrypto
import org.json.JSONObject
import java.io.File
import java.util.Base64
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * Conformance fixture replay — :core must pass the same committed
 * fixtures (apps/shared/fixtures) as the reference TypeScript
 * implementation and the Swift port. Generated by tools/conformance;
 * regenerate with `npm run fixtures`.
 *
 * entitlement.json is deliberately not replayed: token verification is
 * server-side only (clients send the token opaquely).
 */
class FixtureTest {
    companion object {
        val fixturesDir: File = run {
            var dir = File(System.getProperty("user.dir")).absoluteFile
            while (true) {
                val candidate = File(dir, "apps/shared/fixtures")
                if (candidate.isDirectory) return@run candidate
                dir = dir.parentFile ?: error("apps/shared/fixtures not found")
            }
            @Suppress("UNREACHABLE_CODE")
            error("unreachable")
        }
    }

    private fun fixture(name: String): JSONObject =
        JSONObject(File(fixturesDir, name).readText())

    private fun objects(fx: JSONObject, key: String): List<JSONObject> {
        val array = fx.getJSONArray(key)
        return (0 until array.length()).map { array.getJSONObject(it) }
    }

    private fun hex(s: String): ByteArray = SyncCrypto.fromHex(s)

    private fun b64(s: String): ByteArray = Base64.getDecoder().decode(s)

    private fun assertSimilar(a: JSONObject, b: Any, label: String) {
        assertTrue(a.similar(b), "$label: $a != $b")
    }

    @Test
    fun hkdfDerivations() {
        val fx = fixture("hkdf.json")
        val cases = objects(fx, "cases")
        assertTrue(cases.size >= 4)
        for (c in cases) {
            val name = c.getString("name")
            val keys = SyncCrypto.deriveKeys(hex(c.getString("rootSecretHex"))).getOrNull()
                ?: fail("$name: derivation failed")
            assertEquals(c.getString("encKeyHex"), SyncCrypto.toHex(keys.encKey), name)
            assertEquals(c.getString("authTokenHex"), keys.authToken, name)
            assertEquals(c.getString("householdIdHex"), keys.householdId, name)
        }
        for (c in objects(fx, "invalid")) {
            assertTrue(
                SyncCrypto.deriveKeys(hex(c.getString("rootSecretHex"))) is SitrResult.Err,
                c.getString("name"),
            )
        }
    }

    @Test
    fun blobGoldenAndErrors() {
        val fx = fixture("blob.json")
        val golden = fx.getJSONObject("golden")
        val keys = SyncCrypto.deriveKeys(hex(golden.getString("rootSecretHex"))).getOrNull()
            ?: fail("derivation failed")

        val blob = b64(golden.getString("blobB64"))
        val state = Household.openState(blob, keys.encKey).getOrNull()
            ?: fail("golden blob must open")
        assertSimilar(Household.toJSONObject(state), golden.get("stateJson"), "opened state")

        // Seal the exact plaintext with the fixed nonce: byte-identical blob.
        val sealed = SyncCrypto.seal(
            golden.getString("plaintextUtf8").toByteArray(Charsets.UTF_8),
            keys.encKey,
            hex(golden.getString("nonceHex")),
        ).getOrNull() ?: fail("seal failed")
        assertTrue(sealed.contentEquals(blob), "sealing the fixture plaintext must reproduce the blob")

        for (e in objects(fx, "errors")) {
            val name = e.getString("name")
            val key = if (e.has("rootSecretHex")) {
                SyncCrypto.deriveKeys(hex(e.getString("rootSecretHex"))).getOrNull()
                    ?: fail("$name: derivation failed")
            } else keys
            assertTrue(
                Household.openState(b64(e.getString("blobB64")), key.encKey) is SitrResult.Err,
                name,
            )
        }
    }

    @Test
    fun pairingCodes() {
        val fx = fixture("pairing.json")
        for (c in objects(fx, "canonical")) {
            val name = c.getString("name")
            val secret = hex(c.getString("rootSecretHex"))
            val code = c.getString("code")
            assertEquals(code, PairingCode.encode(secret), name)
            val decoded = PairingCode.decode(code).getOrNull() ?: fail("$name: decode failed")
            assertTrue(decoded.contentEquals(secret), name)
        }
        for (c in objects(fx, "decodeOk")) {
            val name = c.getString("name")
            val decoded = PairingCode.decode(c.getString("code")).getOrNull()
                ?: fail("$name: decode failed")
            assertEquals(c.getString("rootSecretHex"), SyncCrypto.toHex(decoded), name)
        }
        for (c in objects(fx, "decodeError")) {
            assertTrue(
                PairingCode.decode(c.getString("code")) is SitrResult.Err,
                c.getString("name"),
            )
        }
    }

    @Test
    fun crc16Vectors() {
        val fx = fixture("crc16.json")
        for (c in objects(fx, "cases")) {
            assertEquals(
                c.getString("crcHex"),
                "%04x".format(PairingCode.crc16(hex(c.getString("inputHex")))),
                c.getString("name"),
            )
        }
    }

    @Test
    fun mergeWinners() {
        val fx = fixture("merge.json")
        for (c in objects(fx, "cases")) {
            val name = c.getString("name")
            val a = Household.sanitize(c.get("a")).getOrNull()
                ?: fail("$name: fixture state a must sanitize")
            val b = Household.sanitize(c.get("b")).getOrNull()
                ?: fail("$name: fixture state b must sanitize")
            val winner = Household.merge(a, b)
            val expected = if (c.getString("winner") == "a") c.get("a") else c.get("b")
            assertSimilar(Household.toJSONObject(winner), expected, name)
        }
    }

    @Test
    fun gateTableExhaustively() {
        val fx = fixture("gate.json")
        val cases = objects(fx, "cases")
        assertEquals(120, cases.size)
        for (c in cases) {
            val kind = assertNotNull(MutationKind.fromWire(c.getString("kind")))
            val role =
                if (c.isNull("role")) null else HouseholdRole.fromWire(c.getString("role"))
            val verdict = Gate.gateMutation(
                kind,
                GateContext(
                    managedLockOptions = c.getBoolean("managedLockOptions"),
                    role = role,
                    hasPin = c.getBoolean("hasPin"),
                ),
            )
            val expected = c.getJSONObject("verdict")
            val label = "${kind.wire} lock=${c.getBoolean("managedLockOptions")} " +
                "role=${c.opt("role")} pin=${c.getBoolean("hasPin")}"
            if (expected.getBoolean("allowed")) {
                assertEquals(
                    MutationVerdict.Allowed(expected.getBoolean("requiresPin")),
                    verdict,
                    label,
                )
            } else {
                val reason = MutationVerdict.Reason.entries
                    .first { it.wire == expected.getString("reason") }
                assertEquals(MutationVerdict.Refused(reason), verdict, label)
            }
        }
    }

    @Test
    fun sanitizeCases() {
        val fx = fixture("sanitize.json")
        for (c in objects(fx, "cases")) {
            val name = c.getString("name")
            val result = Household.sanitize(c.opt("raw"))
            if (c.getBoolean("ok")) {
                val state = result.getOrNull() ?: fail("$name: expected success")
                assertSimilar(Household.toJSONObject(state), c.get("sanitized"), name)
            } else {
                assertTrue(result is SitrResult.Err, "$name: expected failure")
            }
        }
    }

    @Test
    fun pinGoldenAndBackoff() {
        val fx = fixture("pin.json")
        val golden = fx.getJSONObject("golden")
        val hashed = Pin.hash(
            golden.getString("pin"),
            hex(golden.getString("saltHex")),
            golden.getInt("iterations"),
        )
        assertEquals(golden.getString("hashHex"), SyncCrypto.toHex(hashed))

        val record = assertNotNull(Household.sanitizePinRecord(golden.getJSONObject("record")))
        assertTrue(Pin.verify(golden.getString("pin"), record))
        assertTrue(!Pin.verify(golden.getString("wrongPin"), record))

        val backoff = fx.getJSONArray("backoff")
        for (i in 0 until backoff.length()) {
            val c = backoff.getJSONObject(i)
            val after = c.getJSONObject("after")
            val got = Pin.backoffAfterFailure(c.getInt("priorCount"), c.getDouble("now"))
            assertEquals(after.getInt("count"), got.count)
            assertEquals(after.getDouble("lockedUntil"), got.lockedUntil)
        }
    }
}
