/// Conformance fixture replay — SitrCore must pass the same committed
/// fixtures (apps/shared/fixtures) as the reference TypeScript
/// implementation and the Kotlin port. Generated by tools/conformance;
/// regenerate with `npm run fixtures`.
///
/// entitlement.json is deliberately not replayed here: token verification
/// is server-side only, and the iOS app is join-only (it never even
/// handles tokens).
import Foundation
import Testing

@testable import SitrCore

let fixturesDir: URL = {
    // Walk up from this source file to the repo root (the directory
    // containing apps/shared/fixtures). Works under `swift test` from a
    // checkout, which is how CI runs this suite.
    var url = URL(fileURLWithPath: #filePath)
    while url.pathComponents.count > 1 {
        let candidate = url.appendingPathComponent("apps/shared/fixtures")
        if FileManager.default.fileExists(atPath: candidate.path) {
            return candidate
        }
        url.deleteLastPathComponent()
    }
    fatalError("apps/shared/fixtures not found above \(#filePath)")
}()

func fixture(_ name: String) throws -> [String: Any] {
    let data = try Data(contentsOf: fixturesDir.appendingPathComponent(name))
    return try #require(JSONSerialization.jsonObject(with: data) as? [String: Any])
}

func hexData(_ s: String) -> Data { SyncCrypto.fromHex(s)! }

func b64Data(_ s: String) -> Data { Data(base64Encoded: s)! }

/// JSON-value equality (order-insensitive, NSNumber-normalizing).
func expectJSONEqual(
    _ a: Any, _ b: Any, _ label: String,
    sourceLocation: SourceLocation = #_sourceLocation
) {
    #expect(
        (a as AnyObject).isEqual(b as AnyObject),
        "\(label): \(a) != \(b)",
        sourceLocation: sourceLocation
    )
}

@Suite struct FixtureTests {
    @Test func hkdfDerivations() throws {
        let fx = try fixture("hkdf.json")
        let cases = try #require(fx["cases"] as? [[String: Any]])
        #expect(cases.count >= 4)
        for c in cases {
            let name = c["name"] as? String ?? "?"
            let secret = hexData(try #require(c["rootSecretHex"] as? String))
            guard case .success(let keys) = SyncCrypto.deriveKeys(rootSecret: secret) else {
                Issue.record("\(name): derivation failed")
                return
            }
            #expect(SyncCrypto.toHex(keys.encKey) == c["encKeyHex"] as? String, "\(name)")
            #expect(keys.authToken == c["authTokenHex"] as? String, "\(name)")
            #expect(keys.householdId == c["householdIdHex"] as? String, "\(name)")
        }
        for c in try #require(fx["invalid"] as? [[String: Any]]) {
            let secret = hexData(try #require(c["rootSecretHex"] as? String))
            if case .success = SyncCrypto.deriveKeys(rootSecret: secret) {
                Issue.record("\(c["name"] ?? "?"): expected failure")
            }
        }
    }

    @Test func blobGoldenAndErrors() throws {
        let fx = try fixture("blob.json")
        let golden = try #require(fx["golden"] as? [String: Any])
        let secret = hexData(try #require(golden["rootSecretHex"] as? String))
        guard case .success(let keys) = SyncCrypto.deriveKeys(rootSecret: secret) else {
            Issue.record("derivation failed")
            return
        }

        // Open the golden blob and compare states as JSON values.
        let blob = b64Data(try #require(golden["blobB64"] as? String))
        guard case .success(let state) = Household.openState(blob: blob, encKey: keys.encKey)
        else {
            Issue.record("golden blob must open")
            return
        }
        expectJSONEqual(
            Household.toJSONObject(state),
            try #require(golden["stateJson"]),
            "opened state"
        )

        // Seal the exact plaintext with the fixed nonce: byte-identical blob.
        let plaintext = Data(try #require(golden["plaintextUtf8"] as? String).utf8)
        let nonce = hexData(try #require(golden["nonceHex"] as? String))
        guard
            case .success(let sealed) = SyncCrypto.seal(
                plaintext: plaintext, encKey: keys.encKey, nonce: nonce)
        else {
            Issue.record("seal failed")
            return
        }
        #expect(sealed == blob, "sealing the fixture plaintext must reproduce the blob")

        for e in try #require(fx["errors"] as? [[String: Any]]) {
            let name = e["name"] as? String ?? "?"
            let errBlob = b64Data(try #require(e["blobB64"] as? String))
            var key = keys.encKey
            if let wrongSecretHex = e["rootSecretHex"] as? String {
                guard
                    case .success(let wrongKeys) = SyncCrypto.deriveKeys(
                        rootSecret: hexData(wrongSecretHex))
                else {
                    Issue.record("\(name): derivation failed")
                    return
                }
                key = wrongKeys.encKey
            }
            if case .success = Household.openState(blob: errBlob, encKey: key) {
                Issue.record("\(name): expected failure")
            }
        }
    }

    @Test func pairingCodes() throws {
        let fx = try fixture("pairing.json")
        for c in try #require(fx["canonical"] as? [[String: Any]]) {
            let name = c["name"] as? String ?? "?"
            let secret = hexData(try #require(c["rootSecretHex"] as? String))
            let code = try #require(c["code"] as? String)
            #expect(PairingCode.encode(rootSecret: secret) == code, "\(name)")
            guard case .success(let decoded) = PairingCode.decode(code) else {
                Issue.record("\(name): decode failed")
                return
            }
            #expect(decoded == secret, "\(name)")
        }
        for c in try #require(fx["decodeOk"] as? [[String: Any]]) {
            let name = c["name"] as? String ?? "?"
            guard
                case .success(let decoded) = PairingCode.decode(
                    try #require(c["code"] as? String))
            else {
                Issue.record("\(name): decode failed")
                return
            }
            #expect(SyncCrypto.toHex(decoded) == c["rootSecretHex"] as? String, "\(name)")
        }
        for c in try #require(fx["decodeError"] as? [[String: Any]]) {
            if case .success = PairingCode.decode(try #require(c["code"] as? String)) {
                Issue.record("\(c["name"] ?? "?"): expected failure")
            }
        }
    }

    @Test func crc16Vectors() throws {
        let fx = try fixture("crc16.json")
        for c in try #require(fx["cases"] as? [[String: Any]]) {
            let input = hexData(try #require(c["inputHex"] as? String))
            let expected = try #require(c["crcHex"] as? String)
            #expect(
                String(format: "%04x", PairingCode.crc16(input)) == expected,
                "\(c["name"] as? String ?? "?")"
            )
        }
    }

    @Test func mergeWinners() throws {
        let fx = try fixture("merge.json")
        for c in try #require(fx["cases"] as? [[String: Any]]) {
            let name = c["name"] as? String ?? "?"
            guard
                case .success(let a) = Household.sanitize(c["a"]),
                case .success(let b) = Household.sanitize(c["b"])
            else {
                Issue.record("\(name): fixture states must sanitize")
                return
            }
            let winner = Household.merge(a, b)
            let expected = try #require((c["winner"] as? String) == "a" ? c["a"] : c["b"])
            expectJSONEqual(Household.toJSONObject(winner), expected, name)
        }
    }

    @Test func gateTableExhaustively() throws {
        let fx = try fixture("gate.json")
        let cases = try #require(fx["cases"] as? [[String: Any]])
        #expect(cases.count == 120)
        for c in cases {
            let kindRaw = try #require(c["kind"] as? String)
            let kind = try #require(MutationKind(rawValue: kindRaw))
            let role = (c["role"] as? String).flatMap(HouseholdRole.init(rawValue:))
            let ctx = GateContext(
                managedLockOptions: try #require(c["managedLockOptions"] as? Bool),
                role: role,
                hasPin: try #require(c["hasPin"] as? Bool)
            )
            let verdict = Gate.gateMutation(kind, ctx: ctx)
            let expected = try #require(c["verdict"] as? [String: Any])
            let label =
                "\(kind.rawValue) lock=\(ctx.managedLockOptions) role=\(String(describing: role)) pin=\(ctx.hasPin)"
            if expected["allowed"] as? Bool == true {
                let requiresPin = try #require(expected["requiresPin"] as? Bool)
                #expect(verdict == .allowed(requiresPin: requiresPin), "\(label)")
            } else {
                let reasonRaw = try #require(expected["reason"] as? String)
                let reason = try #require(
                    MutationVerdict.RefusalReason(rawValue: reasonRaw))
                #expect(verdict == .refused(reason: reason), "\(label)")
            }
        }
    }

    @Test func sanitizeCases() throws {
        let fx = try fixture("sanitize.json")
        for c in try #require(fx["cases"] as? [[String: Any]]) {
            let name = c["name"] as? String ?? "?"
            let result = Household.sanitize(c["raw"])
            if c["ok"] as? Bool == true {
                guard case .success(let state) = result else {
                    Issue.record("\(name): expected success")
                    return
                }
                expectJSONEqual(
                    Household.toJSONObject(state),
                    try #require(c["sanitized"]),
                    name
                )
            } else if case .success = result {
                Issue.record("\(name): expected failure")
            }
        }
    }

    @Test func pinGoldenAndBackoff() throws {
        let fx = try fixture("pin.json")
        let golden = try #require(fx["golden"] as? [String: Any])
        let pin = try #require(golden["pin"] as? String)
        let salt = hexData(try #require(golden["saltHex"] as? String))
        let iterations = try #require(golden["iterations"] as? Int)
        let hashed = Pin.hash(pin: pin, salt: salt, iterations: iterations)
        #expect(SyncCrypto.toHex(hashed) == golden["hashHex"] as? String)

        let recordJSON = try #require(golden["record"] as? [String: Any])
        let record = try #require(Household.sanitizePinRecord(recordJSON))
        #expect(Pin.verify(pin: pin, record: record))
        let wrongPin = try #require(golden["wrongPin"] as? String)
        #expect(!Pin.verify(pin: wrongPin, record: record))

        for c in try #require(fx["backoff"] as? [[String: Any]]) {
            let after = try #require(c["after"] as? [String: Any])
            let priorCount = try #require(c["priorCount"] as? Int)
            let nowValue = try #require(c["now"] as? Int)
            let got = Pin.backoffAfterFailure(count: priorCount, now: Double(nowValue))
            let lockedUntil = try #require(after["lockedUntil"] as? Int)
            #expect(got.count == after["count"] as? Int)
            #expect(got.lockedUntil == Double(lockedUntil))
        }
    }
}
